### ISSUE TITLE
Question you are responding to

### ISSUE THREAD

**Issue by shafirahmad** [aimakerspace/ai-practitioner-handbook#83] opened 2022-09-22 10:57 UTC
**Section Outline**
Please list the key points of content you intend to cover for this section
 
 
**Definition of Done**
- [ ] Completed `2-proj-mgmt-tech-lead/translate-technical-jargon.md`
- [ ] Verified against [self-review checklist](https://github.com/aisingapore/ai-practitioner-handbook/blob/main/REVIEWING.md)
- [ ] Added section to [table of contents](https://github.com/aisingapore/ai-practitioner-handbook/blob/main/_toc.yml)
- [ ] Page builds and displays correctly on local machine

**Comment by chuawjk** [comment] 2022-09-27 05:24
@shafirahmad This issue looks like a duplicate of #74. Can I close this?

**Comment by shafirahmad** [comment] 2022-09-27 09:06
Duplicate of #74

**Closed as not planned** 2022-09-27 09:07 UTC
Labels: new-section
